# Generated by Django 2.2.17 on 2020-11-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201126_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='deparment',
            new_name='department',
        ),
    ]
