# Generated by Django 2.2.17 on 2020-11-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201126_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('joining_date',)},
        ),
    ]
