# Generated by Django 2.2.17 on 2020-11-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201130_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('id',)},
        ),
    ]
