# Generated by Django 2.2.17 on 2020-12-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20201130_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('senior developer', 'Senior Developer'), ('trainee', 'Trainee'), ('junior developer', 'Junior Developer'), ('team lead', 'Team Lead')], help_text='Designation', max_length=20),
        ),
    ]
