# Generated by Django 2.2.17 on 2020-12-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201203_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(help_text='Give a brief description about department', null=True),
        ),
    ]
